version: "3.8"

services:
  postgres:
    container_name: notification-center-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dicjer
      POSTGRES_DB: notification_center
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  rabbitmq:
    container_name: notification-center-rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
