version: "3.8"

services:
  postgres:
    container_name: notification-center-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dicjer
      POSTGRES_DB: notification_center
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
